import type { SearchRecord } from "./types";

export const navSearchRecords: SearchRecord[] = [
  { id: "nav-dashboard", group: "Pages", title: "Dashboard", href: "/app" },
  { id: "nav-crm", group: "Pages", title: "CRM", href: "/app/crm" },
  { id: "nav-inbox", group: "Pages", title: "Inbox", href: "/app/communication/inbox" },
  { id: "nav-texting", group: "Pages", title: "Texting", href: "/app/communication/texting" },
  { id: "nav-calling", group: "Pages", title: "Calling", href: "/app/communication/calling" },
  { id: "nav-sales", group: "Pages", title: "Sales", href: "/app/sales" },
  { id: "nav-tx-roles", group: "Pages", title: "Transaction Roles", href: "/app/transactions/roles" },
  {
    id: "nav-tx-checklists",
    group: "Pages",
    title: "Checklist Templates",
    href: "/app/transactions/checklists",
  },
  {
    id: "nav-tx-documents",
    group: "Pages",
    title: "Document Templates",
    href: "/app/transactions/documents",
  },
  { id: "nav-reporting", group: "Pages", title: "Reporting", href: "/app/reporting" },
  { id: "nav-marketing", group: "Pages", title: "Marketing", href: "/app/marketing" },
  { id: "nav-content", group: "Pages", title: "Content", href: "/app/content" },
  { id: "nav-automation", group: "Pages", title: "Automation", href: "/app/automation" },
  { id: "nav-ai", group: "Pages", title: "AI Copilots", href: "/app/ai" },
  { id: "nav-ai-overview", group: "Pages", title: "AI Overview", href: "/app/ai/overview" },
  { id: "nav-ai-assistant", group: "Pages", title: "AI Assistant", href: "/app/ai/assistant" },
  { id: "nav-ai-sales", group: "Pages", title: "Sales Agent", href: "/app/ai/sales-agent" },
  { id: "nav-ai-social", group: "Pages", title: "Social Agent", href: "/app/ai/social-agent" },
  { id: "nav-marketplace", group: "Pages", title: "Marketplace", href: "/app/marketplace" },
  { id: "nav-lead-capture", group: "Pages", title: "Lead Capture", href: "/app/lead-settings/capture" },
  { id: "nav-lead-routing", group: "Pages", title: "Lead Routing", href: "/app/lead-settings/routing" },
  { id: "nav-tags", group: "Pages", title: "Tags", href: "/app/lead-settings/tags" },
  { id: "nav-lead-import", group: "Pages", title: "Lead Import", href: "/app/lead-settings/import" },
  { id: "nav-integrations", group: "Pages", title: "Integrations", href: "/app/settings/integrations" },
  { id: "nav-organization", group: "Pages", title: "My Organization", href: "/app/settings/organization" },
  { id: "nav-vendor", group: "Pages", title: "Vendor / Partner", href: "/app/settings/vendor" },
  { id: "nav-profile", group: "Pages", title: "Profile settings", href: "/app/settings/profile" },
  { id: "nav-account", group: "Pages", title: "Account and Security", href: "/app/settings/account" },
  { id: "nav-notif", group: "Pages", title: "Notifications", href: "/app/settings/notifications" },
  {
    id: "nav-personal-reporting",
    group: "Pages",
    title: "Personal Reporting",
    href: "/app/settings/reporting",
  },
  { id: "nav-help", group: "Help", title: "Learning Hub", href: "/app/help" },
  { id: "nav-docs", group: "Help", title: "Official docs", href: "/app/help/docs" },
  { id: "nav-faq", group: "Help", title: "FAQ", href: "/app/help/faq" },
  { id: "nav-tutorials", group: "Help", title: "Tutorials", href: "/app/help/tutorials" },
  { id: "nav-glossary", group: "Help", title: "Glossary", href: "/app/help/glossary" },
];
